name: Prepare Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    name: Build Release Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up toolchain
        run: |
          sudo apt-get install -y gcc-mingw-w64
          rustup target add x86_64-unknown-linux-gnu
          rustup target add x86_64-pc-windows-gnu
          mkdir dist
      - name: Build Linux
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu --verbose
          mv target/x86_64-unknown-linux-gnu/release/speedometer dist/speedometer-x86_64-linux
      - name: Build Windows
        run: |
          cargo build --release --target x86_64-pc-windows-gnu --verbose
          mv target/x86_64-pc-windows-gnu/release/speedometer.exe dist/speedometer-x86_64-windows.exe
      - name: Automatic Release With Assets
        uses: softprops/action-gh-release@v0.1.15
        with:
          draft: true
          prerelease: true
          files: |
            dist/*
