name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
---
name: Prepare Release

on:
  push:
    tags:
    - "v*"

jobs:
  build-release:
    strategy:
      matrix:
        target:
        - x86_64-unknown-linux-gnu
        - x86_64-pc-windows-gnu
    name: Build Release Binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up toolchain
      run: |
        rustup target add x86_64-unknown-linux-gnu
        rustup target add x86_64-pc-windows-gnu
        mkdir dist
    - name: Build Linux
      run: |
        cargo build --release --target x86_64-unknown-linux-gnu --verbose
        mv target/release/speedometer dist/speedometer-x86_64-linux
    - name: Build Windows
      run: |
        cargo build --release --target x86_64-pc-windows-gnu --verbose
        mv target/release/speedometer.exe dist/speedometer-x86_64-windows
    - name: Automatic Release With Assets
      uses: ianlapham/release-and-build@v1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        draft: true
        prerelease: true
        files: |
          dist/*
        
